"""elminar update_at en tabla Note

Revision ID: a9d1f081a033
Revises: bc166f743569
Create Date: 2025-07-29 17:26:21.994233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d1f081a033'
down_revision: Union[str, Sequence[str], None] = 'bc166f743569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_update_at'), table_name='note')
    op.drop_column('note', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('update_at', sa.DATETIME(), nullable=False))
    op.create_index(op.f('ix_note_update_at'), 'note', ['update_at'], unique=False)
    # ### end Alembic commands ###
